In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Classroom/Data Science/students_data.csv")
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira AHMED,16.0,female,11,75.0,NaN,66,10/06/2022,excellent
1,101,shams abid,16.0,Male,10th,74.0,95,94,10/06/2022,GOOD
2,102,hamza SHAH,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira AHMED,16.0,FEMALE,10,NaN,missing,62,10/06/2022,average
4,104,SARA ALI,16.0,male,11,NaN,96,64,10/06/2022,GOOD
5,105,Maha khan,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,aliza nasir,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,SARA ALI,17.0,female,12,NaN,63,62,11/06/2022,excellent
8,108,Maha khan,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,nida Zubair,17.0,female,12,NaN,missing,97,10/06/2022,needs improvement
10,110,ahmed noor,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,aliza nasir,16.0,FEMALE,11th,NaN,missing,95,10/06/2022,average
12,112,SAIRA nasir,17.0,female,11,NaN,87,89,10/06/2022,poor
13,113,SAIRA nasir,17.0,female,10,NaN,NaN,98,06/12/2022,Average
14,114,aliza nasir,17.0,male,12,NaN,91,67,11/06/2022,poor
15,115,ahmed noor,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,hamza SHAH,NaN,Female,11,NaN,NaN,72,11/06/2022,excellent
17,117,aliza nasir,18.0,male,11th,67.0,74,81,10/06/2022,GOOD
18,118,aliza nasir,17.0,Male,10,100.0,74,62,11/06/2022,average
19,119,SAIRA nasir,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,SARA ALI,17.0,Male,10,NaN,missing,89,10/06/2022,average
21,121,shams abid,18.0,female,11,66.0,72,94,10/06/2022,Average
22,122,SARA ALI,17.0,MALE,11th,75.0,NaN,66,10/06/2022,good student
23,123,Zunaira AHMED,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,shams abid,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Maha khan,17.0,Male,12,94.0,80,63,10/06/2022,Average
26,126,shams abid,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,aliza nasir,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,SARA ALI,17.0,female,11,NaN,64,89,10/06/2022,average
29,129,SAIRA nasir,17.0,FEMALE,11,NaN,64,83,11/06/2022,Average
30,129,SAIRA nasir,17.0,FEMALE,11,NaN,64,83,11/06/2022,Average

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     31 non-null     int64
 1   name           31 non-null     object
 2   age            28 non-null     float64
 3   gender         31 non-null     object
 4   grade          31 non-null     object
 5   math_score     13 non-null     float64
 6   english_score  23 non-null     object
 7   science_score  31 non-null     int64
 8   enrolled_date  31 non-null     object
 9   remarks        31 non-null     object
dtypes: float64(2), int64(2), object(6)
memory usage: 2.6+ KB

In [ ]:
df.dtypes

student_id         int64
name              object
age              float64
gender            object
grade             object
math_score       float64
english_score     object
science_score      int64
enrolled_date     object
remarks           object
dtype: object

## Data Cleaning

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
dtype: bool

In [ ]:
df = df.drop_duplicates()
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira AHMED,16.0,female,11,75.0,NaN,66,10/06/2022,excellent
1,101,shams abid,16.0,Male,10th,74.0,95,94,10/06/2022,GOOD
2,102,hamza SHAH,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira AHMED,16.0,FEMALE,10,NaN,missing,62,10/06/2022,average
4,104,SARA ALI,16.0,male,11,NaN,96,64,10/06/2022,GOOD
5,105,Maha khan,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,aliza nasir,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,SARA ALI,17.0,female,12,NaN,63,62,11/06/2022,excellent
8,108,Maha khan,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,nida Zubair,17.0,female,12,NaN,missing,97,10/06/2022,needs improvement
10,110,ahmed noor,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,aliza nasir,16.0,FEMALE,11th,NaN,missing,95,10/06/2022,average
12,112,SAIRA nasir,17.0,female,11,NaN,87,89,10/06/2022,poor
13,113,SAIRA nasir,17.0,female,10,NaN,NaN,98,06/12/2022,Average
14,114,aliza nasir,17.0,male,12,NaN,91,67,11/06/2022,poor
15,115,ahmed noor,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,hamza SHAH,NaN,Female,11,NaN,NaN,72,11/06/2022,excellent
17,117,aliza nasir,18.0,male,11th,67.0,74,81,10/06/2022,GOOD
18,118,aliza nasir,17.0,Male,10,100.0,74,62,11/06/2022,average
19,119,SAIRA nasir,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,SARA ALI,17.0,Male,10,NaN,missing,89,10/06/2022,average
21,121,shams abid,18.0,female,11,66.0,72,94,10/06/2022,Average
22,122,SARA ALI,17.0,MALE,11th,75.0,NaN,66,10/06/2022,good student
23,123,Zunaira AHMED,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,shams abid,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Maha khan,17.0,Male,12,94.0,80,63,10/06/2022,Average
26,126,shams abid,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,aliza nasir,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,SARA ALI,17.0,female,11,NaN,64,89,10/06/2022,average
29,129,SAIRA nasir,17.0,FEMALE,11,NaN,64,83,11/06/2022,Average

In [ ]:
# df.loc[0,"name"]
# df["name"].str.lower().str.title()

# # Both ways achieve the exact same result
# df["name"] = df["name"].str.lower().str.title()

# Best practice
df.loc[:, "name"] = df["name"].str.lower().str.title()
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10th,74.0,95,94,10/06/2022,GOOD
2,102,Hamza Shah,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,FEMALE,10,NaN,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,male,11,NaN,96,64,10/06/2022,GOOD

In [ ]:
df["gender"].unique()

array(['female', 'Male', 'MALE', 'FEMALE', 'male', 'Female'], dtype=object)

In [ ]:
# Both ways achieve the exact same result
# df["gender"] = df["gender"].str.lower().str.title()

# Best practice
df.loc[:, "gender"] = df["gender"].str.lower().str.title()

In [ ]:
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10th,74.0,95,94,10/06/2022,GOOD
2,102,Hamza Shah,NaN,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,NaN,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,NaN,96,64,10/06/2022,GOOD

In [ ]:
df["grade"]

0       11
1     10th
2       10
3       10
4       11
5       10
6       11
7       12
8       12
9       12
10    11th
11    11th
12      11
13      10
14      12
15      12
16      11
17    11th
18      10
19    11th
20      10
21      11
22    11th
23    11th
24    11th
25      12
26    10th
27      12
28      11
29      11
Name: grade, dtype: object

In [ ]:
df["grade"].unique()

array(['11', '10th', '10', '12', '11th'], dtype=object)

In [ ]:
df.loc[:, "grade"] = df["grade"].replace({'10th':'10', '11th':'11'})

In [ ]:
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10,74.0,95,94,10/06/2022,GOOD
2,102,Hamza Shah,NaN,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,NaN,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,NaN,96,64,10/06/2022,GOOD

## Handle Missing Values

In [ ]:
df.isnull()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,True,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,True,True,False,False,False
6,False,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,True,False,False,False,False
12,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,True,True,False,False,False
14,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,True,False,False,True,True,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,True,False,False,False
20,False,False,False,False,False,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,True,False,False,False
23,False,False,False,False,False,True,False,False,False,False
24,False,False,False,False,False,True,True,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,True,False,False,False,False,False,False,False
27,False,False,False,False,False,True,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False
29,False,False,False,False,False,True,False,False,False,False

In [ ]:
df.isnull().sum()

student_id        0
name              0
age               3
gender            0
grade             0
math_score       17
english_score     8
science_score     0
enrolled_date     0
remarks           0
dtype: int64

In [ ]:
# Select the rows that have at least one missing value
df[df.isnull().any(axis=1)].head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
2,102,Hamza Shah,NaN,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,NaN,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,NaN,96,64,10/06/2022,GOOD
5,105,Maha Khan,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement

In [ ]:
df["age"].unique()

array([16., nan, 17., 18.])

In [ ]:
age_mean = df["age"].mean().round(0)
age_mean

np.float64(17.0)

In [ ]:
df.loc[:, "age"] = df["age"].fillna(age_mean)

In [ ]:
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10,74.0,95,94,10/06/2022,GOOD
2,102,Hamza Shah,17.0,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,NaN,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,NaN,96,64,10/06/2022,GOOD

In [ ]:
math_mean = df["math_score"].mean().round(0)
math_mean

np.float64(74.0)

In [ ]:
df.loc[:, "math_score"] = df["math_score"].fillna(math_mean)
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10,74.0,95,94,10/06/2022,GOOD
2,102,Hamza Shah,17.0,Male,10,74.0,missing,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,74.0,missing,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,74.0,96,64,10/06/2022,GOOD
5,105,Maha Khan,16.0,Female,10,74.0,NaN,83,06/12/2022,needs improvement
6,106,Aliza Nasir,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara Ali,17.0,Female,12,74.0,63,62,11/06/2022,excellent
8,108,Maha Khan,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Nida Zubair,17.0,Female,12,74.0,missing,97,10/06/2022,needs improvement
10,110,Ahmed Noor,17.0,Male,11,65.0,67,100,06/12/2022,excellent
11,111,Aliza Nasir,16.0,Female,11,74.0,missing,95,10/06/2022,average
12,112,Saira Nasir,17.0,Female,11,74.0,87,89,10/06/2022,poor
13,113,Saira Nasir,17.0,Female,10,74.0,NaN,98,06/12/2022,Average
14,114,Aliza Nasir,17.0,Male,12,74.0,91,67,11/06/2022,poor
15,115,Ahmed Noor,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Hamza Shah,17.0,Female,11,74.0,NaN,72,11/06/2022,excellent
17,117,Aliza Nasir,18.0,Male,11,67.0,74,81,10/06/2022,GOOD
18,118,Aliza Nasir,17.0,Male,10,100.0,74,62,11/06/2022,average
19,119,Saira Nasir,17.0,Male,11,73.0,NaN,90,06/12/2022,Good
20,120,Sara Ali,17.0,Male,10,74.0,missing,89,10/06/2022,average
21,121,Shams Abid,18.0,Female,11,66.0,72,94,10/06/2022,Average
22,122,Sara Ali,17.0,Male,11,75.0,NaN,66,10/06/2022,good student
23,123,Zunaira Ahmed,17.0,Female,11,74.0,missing,63,06/12/2022,excellent
24,124,Shams Abid,18.0,Male,11,74.0,NaN,91,06/12/2022,GOOD
25,125,Maha Khan,17.0,Male,12,94.0,80,63,10/06/2022,Average
26,126,Shams Abid,17.0,Male,10,64.0,missing,67,06/12/2022,good student
27,127,Aliza Nasir,16.0,Female,12,74.0,76,80,06/12/2022,poor
28,128,Sara Ali,17.0,Female,11,74.0,64,89,10/06/2022,average
29,129,Saira Nasir,17.0,Female,11,74.0,64,83,11/06/2022,Average

### More Cleaning

In [ ]:
df["english_score"]

0         NaN
1          95
2     missing
3     missing
4          96
5         NaN
6         NaN
7          63
8     missing
9     missing
10         67
11    missing
12         87
13        NaN
14         91
15         91
16        NaN
17         74
18         74
19        NaN
20    missing
21         72
22        NaN
23    missing
24        NaN
25         80
26    missing
27         76
28         64
29         64
Name: english_score, dtype: object

In [ ]:
df.loc[:, "english_score"] = pd.to_numeric(df["english_score"], errors='coerce')

In [ ]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,NaN,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,GOOD
2,102,Hamza Shah,17.0,Male,10,74.0,NaN,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,74.0,NaN,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,GOOD
5,105,Maha Khan,16.0,Female,10,74.0,NaN,83,06/12/2022,needs improvement
6,106,Aliza Nasir,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,excellent
8,108,Maha Khan,16.0,Female,12,80.0,NaN,89,06/12/2022,poor
9,109,Nida Zubair,17.0,Female,12,74.0,NaN,97,10/06/2022,needs improvement
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,excellent
11,111,Aliza Nasir,16.0,Female,11,74.0,NaN,95,10/06/2022,average
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,poor
13,113,Saira Nasir,17.0,Female,10,74.0,NaN,98,06/12/2022,Average
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,poor
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,Average
16,116,Hamza Shah,17.0,Female,11,74.0,NaN,72,11/06/2022,excellent
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,GOOD
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,average
19,119,Saira Nasir,17.0,Male,11,73.0,NaN,90,06/12/2022,Good
20,120,Sara Ali,17.0,Male,10,74.0,NaN,89,10/06/2022,average
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,Average
22,122,Sara Ali,17.0,Male,11,75.0,NaN,66,10/06/2022,good student
23,123,Zunaira Ahmed,17.0,Female,11,74.0,NaN,63,06/12/2022,excellent
24,124,Shams Abid,18.0,Male,11,74.0,NaN,91,06/12/2022,GOOD
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,Average
26,126,Shams Abid,17.0,Male,10,64.0,NaN,67,06/12/2022,good student
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,poor
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,average
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,Average

In [ ]:
# english_mean = df["english_score"].mean().round()
# print(english_mean)
# english_median = df["english_score"].median()
# print(english_median)

df.loc[:, "english_score"] = df["english_score"].fillna(0)
df.head()

/tmp/ipython-input-1793055455.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[:, "english_score"] = df["english_score"].fillna(0)

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,excellent
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,GOOD
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,needs improvement
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,average
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,GOOD

In [ ]:
df["remarks"].unique()

array(['excellent', 'GOOD', 'needs improvement', 'average', 'Good',
       'poor', 'Average', 'good student'], dtype=object)

In [ ]:
# TASK: write code to standardize 'Remarks' column
df.loc[:, "remarks"] = df["remarks"].str.lower().str.title()
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,Excellent
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,Good
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,Needs Improvement
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,Average
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,Good
5,105,Maha Khan,16.0,Female,10,74.0,0.0,83,06/12/2022,Needs Improvement
6,106,Aliza Nasir,17.0,Female,11,64.0,0.0,75,06/12/2022,Good
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,Excellent
8,108,Maha Khan,16.0,Female,12,80.0,0.0,89,06/12/2022,Poor
9,109,Nida Zubair,17.0,Female,12,74.0,0.0,97,10/06/2022,Needs Improvement
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,Excellent
11,111,Aliza Nasir,16.0,Female,11,74.0,0.0,95,10/06/2022,Average
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,Poor
13,113,Saira Nasir,17.0,Female,10,74.0,0.0,98,06/12/2022,Average
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,Poor
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,Average
16,116,Hamza Shah,17.0,Female,11,74.0,0.0,72,11/06/2022,Excellent
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,Good
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,Average
19,119,Saira Nasir,17.0,Male,11,73.0,0.0,90,06/12/2022,Good
20,120,Sara Ali,17.0,Male,10,74.0,0.0,89,10/06/2022,Average
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,Average
22,122,Sara Ali,17.0,Male,11,75.0,0.0,66,10/06/2022,Good Student
23,123,Zunaira Ahmed,17.0,Female,11,74.0,0.0,63,06/12/2022,Excellent
24,124,Shams Abid,18.0,Male,11,74.0,0.0,91,06/12/2022,Good
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,Average
26,126,Shams Abid,17.0,Male,10,64.0,0.0,67,06/12/2022,Good Student
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,Poor
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,Average
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,Average

In [ ]:
df["remarks"].unique()

array(['Excellent', 'Good', 'Needs Improvement', 'Average', 'Poor',
       'Good Student'], dtype=object)

In [ ]:
rem = {'Good Student': 'Good', 'Needs Improvement': 'Poor'}

df.loc[:, "remarks"] = df["remarks"].replace(rem)
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,Excellent
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,Good
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,Poor
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,Average
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,Good
5,105,Maha Khan,16.0,Female,10,74.0,0.0,83,06/12/2022,Poor
6,106,Aliza Nasir,17.0,Female,11,64.0,0.0,75,06/12/2022,Good
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,Excellent
8,108,Maha Khan,16.0,Female,12,80.0,0.0,89,06/12/2022,Poor
9,109,Nida Zubair,17.0,Female,12,74.0,0.0,97,10/06/2022,Poor
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,Excellent
11,111,Aliza Nasir,16.0,Female,11,74.0,0.0,95,10/06/2022,Average
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,Poor
13,113,Saira Nasir,17.0,Female,10,74.0,0.0,98,06/12/2022,Average
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,Poor
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,Average
16,116,Hamza Shah,17.0,Female,11,74.0,0.0,72,11/06/2022,Excellent
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,Good
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,Average
19,119,Saira Nasir,17.0,Male,11,73.0,0.0,90,06/12/2022,Good
20,120,Sara Ali,17.0,Male,10,74.0,0.0,89,10/06/2022,Average
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,Average
22,122,Sara Ali,17.0,Male,11,75.0,0.0,66,10/06/2022,Good
23,123,Zunaira Ahmed,17.0,Female,11,74.0,0.0,63,06/12/2022,Excellent
24,124,Shams Abid,18.0,Male,11,74.0,0.0,91,06/12/2022,Good
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,Average
26,126,Shams Abid,17.0,Male,10,64.0,0.0,67,06/12/2022,Good
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,Poor
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,Average
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,Average

-----
## Encoding Categorical Data
-----

In [ ]:
# create dataframe copy
df2 = df.copy()
df2

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,Excellent
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,Good
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,Poor
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,Average
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,Good
5,105,Maha Khan,16.0,Female,10,74.0,0.0,83,06/12/2022,Poor
6,106,Aliza Nasir,17.0,Female,11,64.0,0.0,75,06/12/2022,Good
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,Excellent
8,108,Maha Khan,16.0,Female,12,80.0,0.0,89,06/12/2022,Poor
9,109,Nida Zubair,17.0,Female,12,74.0,0.0,97,10/06/2022,Poor
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,Excellent
11,111,Aliza Nasir,16.0,Female,11,74.0,0.0,95,10/06/2022,Average
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,Poor
13,113,Saira Nasir,17.0,Female,10,74.0,0.0,98,06/12/2022,Average
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,Poor
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,Average
16,116,Hamza Shah,17.0,Female,11,74.0,0.0,72,11/06/2022,Excellent
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,Good
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,Average
19,119,Saira Nasir,17.0,Male,11,73.0,0.0,90,06/12/2022,Good
20,120,Sara Ali,17.0,Male,10,74.0,0.0,89,10/06/2022,Average
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,Average
22,122,Sara Ali,17.0,Male,11,75.0,0.0,66,10/06/2022,Good
23,123,Zunaira Ahmed,17.0,Female,11,74.0,0.0,63,06/12/2022,Excellent
24,124,Shams Abid,18.0,Male,11,74.0,0.0,91,06/12/2022,Good
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,Average
26,126,Shams Abid,17.0,Male,10,64.0,0.0,67,06/12/2022,Good
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,Poor
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,Average
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,Average

### 1. Label Encoder

Label Encoding is a technique used to convert categorical labels into numerical form. Each unique category is assigned a unique integer value. This is suitable for ordinal data where there is a natural order or ranking between the categories. However, using label encoding on nominal data (where there is no inherent order) can mislead machine learning models into assuming a relationship that doesn't exist.

In [ ]:
from sklearn.preprocessing import LabelEncoder

data = ['Red', 'Green', 'Blue', 'Red']

le = LabelEncoder()
encoded_data = le.fit_transform(data)
print(f"Encoded Data: {encoded_data}")

Encoded Data: [2 1 0 2]

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding
df2['remarks'] = label_encoder.fit_transform(df2['remarks'])
df2

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,1
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,2
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,3
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,0
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,2
5,105,Maha Khan,16.0,Female,10,74.0,0.0,83,06/12/2022,3
6,106,Aliza Nasir,17.0,Female,11,64.0,0.0,75,06/12/2022,2
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,1
8,108,Maha Khan,16.0,Female,12,80.0,0.0,89,06/12/2022,3
9,109,Nida Zubair,17.0,Female,12,74.0,0.0,97,10/06/2022,3
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,1
11,111,Aliza Nasir,16.0,Female,11,74.0,0.0,95,10/06/2022,0
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,3
13,113,Saira Nasir,17.0,Female,10,74.0,0.0,98,06/12/2022,0
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,3
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,0
16,116,Hamza Shah,17.0,Female,11,74.0,0.0,72,11/06/2022,1
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,2
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,0
19,119,Saira Nasir,17.0,Male,11,73.0,0.0,90,06/12/2022,2
20,120,Sara Ali,17.0,Male,10,74.0,0.0,89,10/06/2022,0
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,0
22,122,Sara Ali,17.0,Male,11,75.0,0.0,66,10/06/2022,2
23,123,Zunaira Ahmed,17.0,Female,11,74.0,0.0,63,06/12/2022,1
24,124,Shams Abid,18.0,Male,11,74.0,0.0,91,06/12/2022,2
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,0
26,126,Shams Abid,17.0,Male,10,64.0,0.0,67,06/12/2022,2
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,3
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,0
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,0

### 2. Ordinal Encoding

Ordinal Encoding is similar to Label Encoding but allows you to explicitly define the order of the categories. This is useful when you have ordinal data and want to ensure the numerical representation reflects the inherent ranking.

In [ ]:
print(df2.head())
df2 = df.copy()
print(df2.head)

   student_id           name   age  gender grade  math_score english_score  \
0         100  Zunaira Ahmed  16.0  Female    11        75.0           0.0
1         101     Shams Abid  16.0    Male    10        74.0          95.0
2         102     Hamza Shah  17.0    Male    10        74.0           0.0
3         103  Zunaira Ahmed  16.0  Female    10        74.0           0.0
4         104       Sara Ali  16.0    Male    11        74.0          96.0

   science_score enrolled_date  remarks
0             66    10/06/2022        1
1             94    10/06/2022        2
2             69    06/12/2022        3
3             62    10/06/2022        0
4             64    10/06/2022        2
<bound method NDFrame.head of     student_id           name   age  gender grade  math_score english_score  \
0          100  Zunaira Ahmed  16.0  Female    11        75.0           0.0
1          101     Shams Abid  16.0    Male    10        74.0          95.0
2          102     Hamza Shah  17.0    Male    10        74.0           0.0
3          103  Zunaira Ahmed  16.0  Female    10        74.0           0.0
4          104       Sara Ali  16.0    Male    11        74.0          96.0
5          105      Maha Khan  16.0  Female    10        74.0           0.0
6          106    Aliza Nasir  17.0  Female    11        64.0           0.0
7          107       Sara Ali  17.0  Female    12        74.0          63.0
8          108      Maha Khan  16.0  Female    12        80.0           0.0
9          109    Nida Zubair  17.0  Female    12        74.0           0.0
10         110     Ahmed Noor  17.0    Male    11        65.0          67.0
11         111    Aliza Nasir  16.0  Female    11        74.0           0.0
12         112    Saira Nasir  17.0  Female    11        74.0          87.0
13         113    Saira Nasir  17.0  Female    10        74.0           0.0
14         114    Aliza Nasir  17.0    Male    12        74.0          91.0
15         115     Ahmed Noor  16.0  Female    12        65.0          91.0
16         116     Hamza Shah  17.0  Female    11        74.0           0.0
17         117    Aliza Nasir  18.0    Male    11        67.0          74.0
18         118    Aliza Nasir  17.0    Male    10       100.0          74.0
19         119    Saira Nasir  17.0    Male    11        73.0           0.0
20         120       Sara Ali  17.0    Male    10        74.0           0.0
21         121     Shams Abid  18.0  Female    11        66.0          72.0
22         122       Sara Ali  17.0    Male    11        75.0           0.0
23         123  Zunaira Ahmed  17.0  Female    11        74.0           0.0
24         124     Shams Abid  18.0    Male    11        74.0           0.0
25         125      Maha Khan  17.0    Male    12        94.0          80.0
26         126     Shams Abid  17.0    Male    10        64.0           0.0
27         127    Aliza Nasir  16.0  Female    12        74.0          76.0
28         128       Sara Ali  17.0  Female    11        74.0          64.0
29         129    Saira Nasir  17.0  Female    11        74.0          64.0

    science_score enrolled_date    remarks
0              66    10/06/2022  Excellent
1              94    10/06/2022       Good
2              69    06/12/2022       Poor
3              62    10/06/2022    Average
4              64    10/06/2022       Good
5              83    06/12/2022       Poor
6              75    06/12/2022       Good
7              62    11/06/2022  Excellent
8              89    06/12/2022       Poor
9              97    10/06/2022       Poor
10            100    06/12/2022  Excellent
11             95    10/06/2022    Average
12             89    10/06/2022       Poor
13             98    06/12/2022    Average
14             67    11/06/2022       Poor
15             94    06/12/2022    Average
16             72    11/06/2022  Excellent
17             81    10/06/2022       Good
18             62    11/06/2022    Average
19             90    06/12/2022       Good
20             89    10/06/2022    Average
21             94    10/06/2022    Average
22             66    10/06/2022       Good
23             63    06/12/2022  Excellent
24             91    06/12/2022       Good
25             63    10/06/2022    Average
26             67    06/12/2022       Good
27             80    06/12/2022       Poor
28             89    10/06/2022    Average
29             83    11/06/2022    Average  >

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Initialize OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[['Excellent', 'Good', 'Average', 'Poor']])

# Apply Ordinal Encoding
df2['remarks'] = ordinal_encoder.fit_transform(df2[['remarks']])

print("Ordinal Encoded Data:")
df2

Ordinal Encoded Data:

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Zunaira Ahmed,16.0,Female,11,75.0,0.0,66,10/06/2022,0.0
1,101,Shams Abid,16.0,Male,10,74.0,95.0,94,10/06/2022,1.0
2,102,Hamza Shah,17.0,Male,10,74.0,0.0,69,06/12/2022,3.0
3,103,Zunaira Ahmed,16.0,Female,10,74.0,0.0,62,10/06/2022,2.0
4,104,Sara Ali,16.0,Male,11,74.0,96.0,64,10/06/2022,1.0
5,105,Maha Khan,16.0,Female,10,74.0,0.0,83,06/12/2022,3.0
6,106,Aliza Nasir,17.0,Female,11,64.0,0.0,75,06/12/2022,1.0
7,107,Sara Ali,17.0,Female,12,74.0,63.0,62,11/06/2022,0.0
8,108,Maha Khan,16.0,Female,12,80.0,0.0,89,06/12/2022,3.0
9,109,Nida Zubair,17.0,Female,12,74.0,0.0,97,10/06/2022,3.0
10,110,Ahmed Noor,17.0,Male,11,65.0,67.0,100,06/12/2022,0.0
11,111,Aliza Nasir,16.0,Female,11,74.0,0.0,95,10/06/2022,2.0
12,112,Saira Nasir,17.0,Female,11,74.0,87.0,89,10/06/2022,3.0
13,113,Saira Nasir,17.0,Female,10,74.0,0.0,98,06/12/2022,2.0
14,114,Aliza Nasir,17.0,Male,12,74.0,91.0,67,11/06/2022,3.0
15,115,Ahmed Noor,16.0,Female,12,65.0,91.0,94,06/12/2022,2.0
16,116,Hamza Shah,17.0,Female,11,74.0,0.0,72,11/06/2022,0.0
17,117,Aliza Nasir,18.0,Male,11,67.0,74.0,81,10/06/2022,1.0
18,118,Aliza Nasir,17.0,Male,10,100.0,74.0,62,11/06/2022,2.0
19,119,Saira Nasir,17.0,Male,11,73.0,0.0,90,06/12/2022,1.0
20,120,Sara Ali,17.0,Male,10,74.0,0.0,89,10/06/2022,2.0
21,121,Shams Abid,18.0,Female,11,66.0,72.0,94,10/06/2022,2.0
22,122,Sara Ali,17.0,Male,11,75.0,0.0,66,10/06/2022,1.0
23,123,Zunaira Ahmed,17.0,Female,11,74.0,0.0,63,06/12/2022,0.0
24,124,Shams Abid,18.0,Male,11,74.0,0.0,91,06/12/2022,1.0
25,125,Maha Khan,17.0,Male,12,94.0,80.0,63,10/06/2022,2.0
26,126,Shams Abid,17.0,Male,10,64.0,0.0,67,06/12/2022,1.0
27,127,Aliza Nasir,16.0,Female,12,74.0,76.0,80,06/12/2022,3.0
28,128,Sara Ali,17.0,Female,11,74.0,64.0,89,10/06/2022,2.0
29,129,Saira Nasir,17.0,Female,11,74.0,64.0,83,11/06/2022,2.0

### 3. One-Hot Encoding

One-Hot Encoding is a technique used to convert categorical variables into a numerical format that is suitable for machine learning algorithms. It creates a new binary column for each unique category in the original column. If a row belongs to a specific category, the corresponding column for that category will have a value of 1, and all other category columns will have a value of 0. This method is best for nominal data where there is no inherent order, as it avoids implying any numerical relationship between categories.

In [ ]:
# Apply One-Hot Encoding
df_one_hot= pd.get_dummies(df2['remarks'], prefix='Remark')

print("One-Hot Encoded Data:")
df_one_hot

One-Hot Encoded Data:

    Remark_0.0  Remark_1.0  Remark_2.0  Remark_3.0
0         True       False       False       False
1        False        True       False       False
2        False       False       False        True
3        False       False        True       False
4        False        True       False       False
5        False       False       False        True
6        False        True       False       False
7         True       False       False       False
8        False       False       False        True
9        False       False       False        True
10        True       False       False       False
11       False       False        True       False
12       False       False       False        True
13       False       False        True       False
14       False       False       False        True
15       False       False        True       False
16        True       False       False       False
17       False        True       False       False
18       False       False        True       False
19       False        True       False       False
20       False       False        True       False
21       False       False        True       False
22       False        True       False       False
23        True       False       False       False
24       False        True       False       False
25       False       False        True       False
26       False        True       False       False
27       False       False       False        True
28       False       False        True       False
29       False       False        True       False

### 4. Binary encoding

Binary Encoding is a combination of Hash Encoding and One-Hot Encoding. It first converts each category into an integer, then that integer is converted into its binary representation. The binary digits then form the new columns. This is particularly useful for high-cardinality categorical features where One-Hot Encoding would create too many columns, potentially leading to the "curse of dimensionality".

In [ ]:
# First, install category_encoders library
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.8.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.8.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 4.8 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.8.1

In [ ]:
import category_encoders as ce
# import pandas as pd

# Sample data
# data = ['A', 'B', 'C', 'D', 'E', 'A', 'B']
# df = pd.DataFrame(data, columns=['Category'])


# Initialize BinaryEncoder
encoder = ce.BinaryEncoder(cols=['remarks'])

# Apply Binary Encoding
df_encoded = encoder.fit_transform(df2['remarks'])

print("Binary Encoded Data:")
print(df_encoded)

Binary Encoded Data:
    remarks_0  remarks_1  remarks_2
0           0          0          1
1           0          1          0
2           0          1          1
3           1          0          0
4           0          1          0
5           0          1          1
6           0          1          0
7           0          0          1
8           0          1          1
9           0          1          1
10          0          0          1
11          1          0          0
12          0          1          1
13          1          0          0
14          0          1          1
15          1          0          0
16          0          0          1
17          0          1          0
18          1          0          0
19          0          1          0
20          1          0          0
21          1          0          0
22          0          1          0
23          0          0          1
24          0          1          0
25          1          0          0
26          0          1          0
27          0          1          1
28          1          0          0
29          1          0          0

### 5. Frequency Encoding

Frequency Encoding is a technique that replaces each category with its frequency (or count) in the dataset. Categories that appear more often will have a higher frequency value. This can be useful when the frequency of a category is indicative of the target variable. It can also help reduce the dimensionality of high-cardinality features.

In [ ]:
# # Sample data
# data = ['Apple', 'Banana', 'Apple', 'Orange', 'Banana']
# df = pd.DataFrame(data, columns=['Fruit'])

# Frequency Encoding
frequency_encoding = df2['remarks'].value_counts().to_dict()
print(frequency_encoding)
df2['Remarks_encoded'] = df2['remarks'].map(frequency_encoding)

print("Frequency Encoded Data:")
print(df2)

{2.0: 10, 1.0: 8, 3.0: 7, 0.0: 5}
Frequency Encoded Data:
    student_id           name   age  gender grade  math_score english_score  \
0          100  Zunaira Ahmed  16.0  Female    11        75.0           0.0
1          101     Shams Abid  16.0    Male    10        74.0          95.0
2          102     Hamza Shah  17.0    Male    10        74.0           0.0
3          103  Zunaira Ahmed  16.0  Female    10        74.0           0.0
4          104       Sara Ali  16.0    Male    11        74.0          96.0
5          105      Maha Khan  16.0  Female    10        74.0           0.0
6          106    Aliza Nasir  17.0  Female    11        64.0           0.0
7          107       Sara Ali  17.0  Female    12        74.0          63.0
8          108      Maha Khan  16.0  Female    12        80.0           0.0
9          109    Nida Zubair  17.0  Female    12        74.0           0.0
10         110     Ahmed Noor  17.0    Male    11        65.0          67.0
11         111    Aliza Nasir  16.0  Female    11        74.0           0.0
12         112    Saira Nasir  17.0  Female    11        74.0          87.0
13         113    Saira Nasir  17.0  Female    10        74.0           0.0
14         114    Aliza Nasir  17.0    Male    12        74.0          91.0
15         115     Ahmed Noor  16.0  Female    12        65.0          91.0
16         116     Hamza Shah  17.0  Female    11        74.0           0.0
17         117    Aliza Nasir  18.0    Male    11        67.0          74.0
18         118    Aliza Nasir  17.0    Male    10       100.0          74.0
19         119    Saira Nasir  17.0    Male    11        73.0           0.0
20         120       Sara Ali  17.0    Male    10        74.0           0.0
21         121     Shams Abid  18.0  Female    11        66.0          72.0
22         122       Sara Ali  17.0    Male    11        75.0           0.0
23         123  Zunaira Ahmed  17.0  Female    11        74.0           0.0
24         124     Shams Abid  18.0    Male    11        74.0           0.0
25         125      Maha Khan  17.0    Male    12        94.0          80.0
26         126     Shams Abid  17.0    Male    10        64.0           0.0
27         127    Aliza Nasir  16.0  Female    12        74.0          76.0
28         128       Sara Ali  17.0  Female    11        74.0          64.0
29         129    Saira Nasir  17.0  Female    11        74.0          64.0

    science_score enrolled_date  remarks  Remarks_encoded
0              66    10/06/2022      0.0                5
1              94    10/06/2022      1.0                8
2              69    06/12/2022      3.0                7
3              62    10/06/2022      2.0               10
4              64    10/06/2022      1.0                8
5              83    06/12/2022      3.0                7
6              75    06/12/2022      1.0                8
7              62    11/06/2022      0.0                5
8              89    06/12/2022      3.0                7
9              97    10/06/2022      3.0                7
10            100    06/12/2022      0.0                5
11             95    10/06/2022      2.0               10
12             89    10/06/2022      3.0                7
13             98    06/12/2022      2.0               10
14             67    11/06/2022      3.0                7
15             94    06/12/2022      2.0               10
16             72    11/06/2022      0.0                5
17             81    10/06/2022      1.0                8
18             62    11/06/2022      2.0               10
19             90    06/12/2022      1.0                8
20             89    10/06/2022      2.0               10
21             94    10/06/2022      2.0               10
22             66    10/06/2022      1.0                8
23             63    06/12/2022      0.0                5
24             91    06/12/2022      1.0                8
25             63    10/06/2022      2.0               10
26             67    06/12/2022      1.0                8
27             80    06/12/2022      3.0                7
28             89    10/06/2022      2.0               10
29             83    11/06/2022      2.0               10

Let's provide more comprehensive explanations and examples for each categorical encoding technique.

### Label Encoding - Expanded Explanation and Example

Label Encoding is a fundamental technique for converting categorical variables into numerical format. Each unique category is assigned a unique integer ID. This method is straightforward and computationally efficient.

However, a significant drawback is that it imposes an arbitrary order on the categories. For instance, if you have categories 'A', 'B', and 'C' encoded as 0, 1, and 2, a machine learning model might interpret that 'C' is "greater" than 'B' and 'B' is "greater" than 'A', and that the "distance" between 'A' and 'B' is the same as the "distance" between 'B' and 'C'. This can be misleading for nominal categorical data where there is no inherent order (e.g., colors, countries). This artificial ordering can negatively impact the performance of algorithms that are sensitive to the magnitude of features, such as linear regression or support vector machines.

Label Encoding is most suitable for ordinal categorical data, where the categories have a natural rank or order (e.g., 'Small', 'Medium', 'Large'; 'Low', 'Medium', 'High').

**Here's an expanded example using customer ratings:**

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Sample data: Customer ratings (Ordinal data)
data_ratings = {'Rating': ['Good', 'Excellent', 'Average', 'Good', 'Poor', 'Excellent', 'Average']}
df_ratings = pd.DataFrame(data_ratings)

label_encoder_ratings = LabelEncoder()
df_ratings['Rating_Encoded'] = label_encoder_ratings.fit_transform(df_ratings['Rating'])

print("Original 'Rating' Data:")
print(df_ratings[['Rating']])
print("\nLabel Encoded 'Rating' Data:")
print(df_ratings[['Rating_Encoded']])

# Note: While LabelEncoder works here, it assigns integers based on alphabetical order ('Average'=0, 'Excellent'=1, 'Good'=2, 'Poor'=3),
# which doesn't reflect the natural order of ratings. This is where Ordinal Encoding with defined categories is more appropriate.

### Ordinal Encoding - Expanded Explanation and Example

Ordinal Encoding is specifically designed for ordinal categorical data. Unlike Label Encoding, it allows you to specify the correct order of the categories. This ensures that the numerical representation assigned to each category respects the inherent ranking, providing a more accurate representation for machine learning models.

By providing the `categories` parameter with a list of unique categories in the desired order, the OrdinalEncoder assigns integers based on that specified sequence. This is crucial for models that will use these features, as they can correctly interpret the ordered relationship between categories.

**Here's an expanded example using educational degrees:**

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Sample data: Educational degrees (Ordinal data)
data_degrees = {'Degree': ["High School", "Bachelor's", "Master's", "PhD", "Bachelor's", "High School"]}
df_degrees = pd.DataFrame(data_degrees)

# Define the correct order of degrees
degree_order = ["High School", "Bachelor's", "Master's", "PhD"]

# Initialize OrdinalEncoder with the specified order
ordinal_encoder_degrees = OrdinalEncoder(categories=[degree_order])

# Apply Ordinal Encoding
df_degrees['Degree_Encoded'] = ordinal_encoder_degrees.fit_transform(df_degrees[['Degree']])

print("Original 'Degree' Data:")
print(df_degrees[['Degree']])
print("\nOrdinal Encoded 'Degree' Data:")
print(df_degrees[['Degree_Encoded']])

### One-Hot Encoding - Expanded Explanation and Example

One-Hot Encoding is the go-to method for nominal categorical data. It tackles the issue of artificial ordering by creating binary columns for each unique category. For each observation, the column corresponding to its category is marked with a 1, and all other category columns are marked with a 0.

This approach avoids implying any quantitative relationship between categories. However, it can lead to a significant increase in the number of features, especially if a categorical variable has many unique values (high cardinality). This can result in a sparse dataset (many zeros) and potentially lead to the "curse of dimensionality," which can affect model performance and training time.

Pandas `get_dummies()` function is a convenient way to perform One-Hot Encoding.

**Here's an expanded example using movie genres:**

In [ ]:
import pandas as pd

# Sample data: Movie genres (Nominal data)
data_genres = {'Genre': ['Action', 'Comedy', 'Drama', 'Action', 'Science Fiction', 'Comedy']}
df_genres = pd.DataFrame(data_genres)

# Apply One-Hot Encoding
df_genres_one_hot = pd.get_dummies(df_genres['Genre'], prefix='Genre')

print("Original 'Genre' Data:")
print(df_genres[['Genre']])
print("\nOne-Hot Encoded 'Genre' Data:")
print(df_genres_one_hot)

### Binary Encoding - Expanded Explanation and Example

Binary Encoding is a useful technique for high-cardinality nominal features. It provides a balance between One-Hot Encoding and simpler methods like Label Encoding. It first converts each category to an integer, then represents that integer in binary code. Each bit in the binary code becomes a new binary column.

This method significantly reduces the dimensionality compared to One-Hot Encoding for high-cardinality features while still avoiding the arbitrary ordering of Label Encoding. It is a good option when you have many unique categories and want to reduce the number of features without losing too much information.

The `category_encoders` library provides a `BinaryEncoder`.

**Here's an expanded example using product IDs:**

In [ ]:
import pandas as pd
import category_encoders as ce

# Sample data: Product IDs (High cardinality nominal data)
data_products = {'ProductID': ['A101', 'B205', 'C310', 'A101', 'D400', 'B205', 'E550']}
df_products = pd.DataFrame(data_products)

# Initialize BinaryEncoder
encoder_products = ce.BinaryEncoder(cols=['ProductID'])

# Apply Binary Encoding
df_products_encoded = encoder_products.fit_transform(df_products['ProductID'])

print("Original 'ProductID' Data:")
print(df_products[['ProductID']])
print("\nBinary Encoded 'ProductID' Data:")
print(df_products_encoded)

### Frequency Encoding - Expanded Explanation and Example

Frequency Encoding replaces each category with the number of times it appears in the dataset (its frequency) or its proportion (relative frequency). This method is based on the assumption that the frequency of a category might be predictive of the target variable.

Frequency Encoding doesn't increase the number of features, which is an advantage, especially for high-cardinality features. However, different categories that have the same frequency will be assigned the same numerical value, which could lead to a loss of information if the categories themselves are distinct and the frequency is not the only relevant factor.

**Here's an expanded example using website visitor sources:**

In [ ]:
import pandas as pd

# Sample data: Website visitor source
data_source = {'Source': ['Google', 'Direct', 'Google', 'Social Media', 'Direct', 'Google', 'Social Media', 'Direct']}
df_source = pd.DataFrame(data_source)

# Calculate frequency of each source
frequency_encoding_source = df_source['Source'].value_counts().to_dict()

# Map frequency to the original column
df_source['Source_Encoded'] = df_source['Source'].map(frequency_encoding_source)

print("Original 'Source' Data:")
print(df_source[['Source']])
print("\nFrequency Encoded 'Source' Data:")
print(df_source[['Source_Encoded']])